name: AI Job Hunter Agent

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  run-agent:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print message
        run: echo "AI Job Hunter Agent Running..."
